name: SaintVisionAI Production Deployment

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: saintvisionai-production
  AZURE_WEBAPP_PACKAGE_PATH: "./dist/spa"
  NODE_VERSION: "18.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run tests
        run: npm test --if-present

      - name: Build application
        run: npm run build:client
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Create Azure web.config
        run: |
          cat > dist/spa/web.config << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <rewrite>
                <rules>
                  <rule name="React Router" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/" />
                  </rule>
                </rules>
              </rewrite>
              <staticContent>
                <mimeMap fileExtension=".json" mimeType="application/json" />
              </staticContent>
              <httpCompression>
                <dynamicTypes>
                  <add mimeType="application/json" enabled="true"/>
                </dynamicTypes>
              </httpCompression>
            </system.webServer>
          </configuration>
          EOF

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: production-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Warm up application
        run: |
          sleep 30
          curl -f https://saintvisionai-production.azurewebsites.net/health || true

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment: staging

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-app

      - name: Deploy to staging slot
        uses: azure/webapps-deploy@v2
        with:
          app-name: saintvisionai-production
          slot-name: staging
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
